name: Build and Push Docker Images

on:
  push:
    branches:
      - '*' # Run this workflow on all branches

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build and Install All Modules
        run: |
          mvn clean install -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          IMAGE_NAME=ghcr.io/tatiana-ndoumbeu/xmart-backend
          docker build -t $IMAGE_NAME:latest -f xmart-zity-backend/Dockerfile xmart-zity-backend/
          docker push $IMAGE_NAME:latest

      - name: Build and Push Frontend Image
        run: |
          IMAGE_NAME=ghcr.io/tatiana-ndoumbeu/xmart-frontend
          docker build -t $IMAGE_NAME:latest -f xmart-frontend/Dockerfile xmart-frontend/
          docker push $IMAGE_NAME:latest
